\PassOptionsToPackage{unicode=true}{hyperref} % options for packages loaded elsewhere
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provides euro and other symbols
\else % if luatex or xelatex
  \usepackage{unicode-math}
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage[]{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\usepackage{hyperref}
\hypersetup{
            pdftitle={SkillCraft Multivariant Regression},
            pdfauthor={Arrington Walters},
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs}
% Fix footnotes in tables (requires footnote package)
\IfFileExists{footnote.sty}{\usepackage{footnote}\makesavenoteenv{longtable}}{}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{0}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

% set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother


\title{SkillCraft Multivariant Regression}
\author{Arrington Walters}
\date{11/4/2020}

\begin{document}
\maketitle

\hypertarget{introduction}{%
\section{Introduction}\label{introduction}}

Videogames are one of my favorite past times. As a player who
participates in ranked play, I've always kept my eye on the forefront of
global competitions. One of the most notable games to establish an
international competitive scene backed by paid professionals was the
real-time strategy game (RTS) Starcraft II (SC2). In 2013 the top 10
starcraft players made nearly four-million dollars from their combined
winnings (``Winnings: 2019 - Liquipedia - the Starcraft Ii
Encyclopedia'' n.d.). Watching top-caliber players reflexes and control
is astonishing to even seasoned videogame enthusiasts. At the 2019
StarCraft II World Championship Finale, many others and I packed into
the arena to see what these professions could do firsthand.

\begin{figure}
\centering
\includegraphics{./inline/WCS.png}
\caption{`(``Congrats to the Starcraft Ii Wcs Global Finals Champion! -
Blizzcon'' n.d.)'}
\end{figure}

The eye-watering speeds they perform at is universally referenced in
gaming terminology as actions per minute (APMS). Professionals take
actions at such fast speeds (high APMS); it becomes challenging to
follow their overall strategy. Past pondering their sheer speed, I found
it difficult to distinctly define what made these players high skilled.

To learn more about what defines talent in SC2 this analysis, we will
explore in-game metrics to explain rank in competitive mode. The dataset
used was provided by
\href{https://archive.ics.uci.edu/ml/datasets/SkillCraft1+Master+Table+Dataset}{`(``UCI
Machine Learning Repository: SkillCraft1 Master Table Dataset Data Set''
n.d.)'}.

\hypertarget{goal}{%
\subsection{Goal}\label{goal}}

To model the response LeagueIndex a sample of player data from a 2013
ranked season of Starcraft will be explored. The predictors provided
summarize in-game performance metrics for a season by player (GameID).
The modeling process will consider all the predictor variables and then
trim down until only significant predictors remain. Variables will be
vetted for multicollinearity, and finally, the model will be explored to
see if the BLUE assumptions hold.

The goal of this analysis will be to test the explanatory power of APMs
and other predictors that are less commonly discussed.

\hypertarget{limitations-of-the-model}{%
\subsection{Limitations of the Model}\label{limitations-of-the-model}}

The multivariate regression model used for the midterm two portions of
this study explores the linear estimation of mean response of
LeagueIndex estimated by predictors in the design matrix \(X\).

The assumptions of this model's explanatory power depend on the residual
error being gaussian. Considering LeagueIndex is an ordinal variable, it
is doubtful, if not impossible, for the residuals to be statistically
normal.

A more suitable form of a model for this regression would be based on a
Polytonomous Logistic Regression for Ordinal Response (Proportional Odds
Model) (``Ordinal Logistic Regression \textbar{} R Data Analysis
Examples'' n.d.). These methods will be revisited for the final portion
of this analysis.

\hypertarget{the-data-exploring}{%
\section{The Data Exploring}\label{the-data-exploring}}

This dataset is a sample of averaged in-game metrics of Starcraft II
players who participate in 2013 ranked play. The variables are as
follows:

\begin{verbatim}
##  [1] "GameID"               "LeagueIndex"          "Age"                 
##  [4] "HoursPerWeek"         "TotalHours"           "APM"                 
##  [7] "SelectByHotkeys"      "AssignToHotkeys"      "UniqueHotkeys"       
## [10] "MinimapAttacks"       "MinimapRightClicks"   "NumberOfPACs"        
## [13] "GapBetweenPACs"       "ActionLatency"        "ActionsInPAC"        
## [16] "TotalMapExplored"     "WorkersMade"          "UniqueUnitsMade"     
## [19] "ComplexUnitsMade"     "ComplexAbilitiesUsed"
\end{verbatim}

The appendix covers each in-depth, but the following are highlighted as
a preface.

\textbf{LeagueIndex} The levels of LeagueIndex range 1-8 corresponding
to player ranks Bronze, Silver, Gold, Platinum, Diamond, Master, Grand
Master. Visible to the player in-game, each medal bronze through master
is subdivided into divisions 1-5. Each division is once again but
instead by divisions but is instead unbounded in terms of rank points
(``Leagues: 2019 - Liquipedia - the Starcraft Ii Encyclopedia'' n.d.).
The rating system similar to an Elo rating system standard in chess.
Elo's designs have an extreme value distribution, also known as a Gumbel
distribution (``ELO Rating Sysem in Chess'' n.d.). Although a Gumbel
distribution would be problematic as a nonnormal response, it would
provide some much-needed continuity by transforming players
\textbf{LeagueIndex} into a more continuous experimental variable.
Unfortunately, these subdivisions are either unavailable or would
require far too much cleaning for the scope of this analysis.

The limitation of predicting this ordinal response will be revisited
more precisely, along with the exploration, modeling, and predictions.

The following are the icon's earned for players who achieve related rank
by the end of a given season. The legends for the following plots are
styled to match.

\begin{figure}
\centering
\includegraphics{./inline/StarCraft-II-Leagues.png}
\caption{`(``Congrats to the Starcraft Ii Wcs Global Finals Champion! -
Blizzcon'' n.d.)'}
\end{figure}

\textbf{Actions Per Minute (APMs)} - APMs apply to various games but are
the standard metric for analyzing proficiency of players at RTS games;
its theorized skills like this provide a great advantage to players
(``APM Definition'' n.d.). Action quickness alone does not capture the
strategy or macro/micro-skills, so these additional predictors may add
some unique color in hopes of further explaining what makes players
skilled.

\textbf{Perception-Action Cycles (PACs)} - are the circular flow of
information between an organism and its environment where a
sensor-guided sequence of behaviors is iteratively followed towards a
goal (``Perception-Action Cycle - Models, Architectures, and Hardware
\textbar{} Vassilis Cutsuridis \textbar{} Springer'' n.d.). In this
data-set, PACs are aggregate of screen movements where PAC is a screen
fixation of containing at least one action (``UCI Machine Learning
Repository: SkillCraft1 Master Table Dataset Data Set'' n.d.).

\hypertarget{cleanliness}{%
\section{Cleanliness}\label{cleanliness}}

The missing values are related exclusively to players with LeagueIndex
equivalent to Professional Players (8). The 55 players with
LeagueIndex==8 the age data is NA and the HoursPerWeek are 0.
LeagueIndexes 1-7 are obtainable playing matches in the base game and
ranking up by winning. To be a professional, you would have to be part
of a team that has no direct role in the broader matchmaking system.
This study aims to understand how players go from being average to good,
less so elite to best. The 55 values associated with professionals will
be dropped to resolve both issues.

Another issue with \textbf{LeagueIndex} is that \textbf{LeagueIndex} 1-6
may contain many players, while \textbf{LeagueIndex} 7-Grandmaster may
only include some set range of players targeted at 1000 total per region
(``Leagues: 2019 - Liquipedia - the Starcraft Ii Encyclopedia'' n.d.).
Dropping \textbf{LeagueIndex}=7 would be a step towards normality.
Considering this multivariate linear model is already hampered by its
selected application on an ELO system, \textbf{LeagueIndex}=7 will be
kept to preserve a potential insight into Starcraft II players' larger
population.

In addition to the missing values we have a clear error with the
\textbf{TotalHours} of one player. \(GameID = 5140\) has 1,000,000
\textbf{TotalHours} that equates to 114 years of game time.

If we assumed one extra zero had been added at the end of the player's
\textbf{TotalHours}, it equates to 14 years of playing time on a game
that is only ten years old as of 2020. Removing two zeros equates to 1.4
years of playing time and three zeros in 51.1 days of played time, both
that seem just as realistic. There is not a clear path to extrapolate
this player's true \textbf{TotalHours}, so their data will be dropped
from the analysis. This was initially detected during modeling but
brought earlier into that analysis.

Finally, performing a necessary inspection on \textbf{HoursPerWeek}, a
max value of 168 was discovered. Considering there are 168 hours in a
week, it's not plausible for an individual player to do this. There
could be multiple players using this account, making this possible.
Another prospect is that this player is an AI like google's DeepMind
(``AlphaStar: Mastering the Real-Time Strategy Game Starcraft Ii
\textbar{} Deepmind'' n.d.). Either way, this observation will be kept
because what is the realistic cutoff for hours per week is not apparent,
and after removing this observation, the next max value is 140, which
seems almost as unrealistic.

It's worth noting that dropping any amount of high hour outliers still
far from combats all the potential abnormalities encountered through the
use of \textbf{HoursPerWeek} and \textbf{TotalHours}. Multiple players
could be using any of the accounts, even if either time played variable
is not relatively large. Potentially exacerbating the left-extrema is
that nothing prevents one player from smurfing multiple times. Smurfing
is when a player makes an additional accounts (``What Is a Smurf
Account? Everything You Need to Know \textbar{} Lol-Smurfs'' n.d.). A
common reason for doing this is to dominate the competition until their
Elo rating adapts to their actual skill level.

\hypertarget{converting-units}{%
\subsection{Converting Units}\label{converting-units}}

Some of the time, averaged metrics are per SC2 timestamp while others
are per millisecond. All-time metrics in timestamps or milliseconds will
be converted to seconds to help with interpretability. There are roughly
88.5 timestamps per second, so each metric in timestamps will be
multiplied by 88.5 (``UCI Machine Learning Repository: SkillCraft1
Master Table Dataset Data Set'' n.d.). Some of the time-averaged metrics
are per millisecond. This transformation is linear and will not affect
our model's assumptions.

\hypertarget{summary-statistics-and-plots}{%
\subsection{Summary Statistics and
Plots}\label{summary-statistics-and-plots}}

\hypertarget{gaussianity-of-the-response}{%
\subsubsection{Gaussianity of the
Response}\label{gaussianity-of-the-response}}

When using the Shapiro-Wilk W test on response \textbf{LeagueIndex}, the
null hypothesis that the sample comes from normally distribution can be
rejected. Besides the obvious issues with performing a W test with an
ordinal response with a potentially underlying Gumbel distribution, the
response has a negative skew with a mean of 4.12. Furthermore, there is
no reason that \textbf{LeagueIndexes} are uniforming spaced in terms of
overall rank or skill.

\includegraphics{skillcraft_regression_files/figure-latex/unnamed-chunk-4-1.pdf}

\hypertarget{correlation-plot}{%
\subsubsection{Correlation Plot}\label{correlation-plot}}

Using the correlation matrix provided below, we can see that LeagueIndex
has a relatively strong correlation with \textbf{APM, SelectByHotkeys,
AssignToHotkeys, NumberofPACs, GapBetweenPACs, and Action Latency}. Some
of these predictors may be the best choices for the model. However, it's
worth noting that many of the predictor values also have reasonably
strong correlations within themselves, which may cause multiple
colinearities in a model. This is not too surprising because many of
these metrics capture the rate of actions in slightly different forms.
For example, \textbf{APM} and \textbf{NumberOfPacs} likely have a strict
mathematical relationship where approximately.
\[NumberOfPACs \approx APM*MatchDurationMinutes\] The slight differences
between these metrics could have some deep explanatory power, but that
level of exploration is beyond the scope of this analysis. Focusing
exclusively on \textbf{APM} fits into an Occam's razor approach by
minimizing \(span(X)\).

The following columns will be dropped as they may confound with
\textbf{APMs, ActionLatency, GapBetweenPACs},\footnote{An additional
  issue with this predictor is that it does not seem to line up with the
  time units in the description. Before and after the unit
  transformation \textbf{GapBetweenPACs} results in a mean is 11.3094444
  hours.)}\textbf{ NumberofPACS, SelectbyHotkey, and ActionsInPAC.}

\includegraphics{skillcraft_regression_files/figure-latex/unnamed-chunk-5-1.pdf}

\hypertarget{visual-trend-analysis}{%
\subsubsection{Visual Trend Analysis}\label{visual-trend-analysis}}

Visually determining trends between the predictors and responding with
an ordinal response is best done with alternatives to scatter plots.
Violin plots will be used to gauge the linearity concerning the response
and distribution with the variable at the varying levels (``A Complete
Guide to Violin Plots \textbar{} Tutorial by Chartio'' n.d.). The
appendix covers more details concerning why Violin plots were chosen.

\textbf{MinimapAttacks, HoursPerweek, TotalHours, MinimapRightClicks,
ComplexUnitsMade, ComplexAbilitiesUsed} all have very long right tails.
In search of gaussian predictors, these predictors could be transformed
for linearity. Although a transform would have affected the
explanation's simplicity.\footnote{A log transformation would be
  preferable, but enough observations by GameID that contain at least 0
  in the related predictor entry would have to drop observations
  containing \(-\infty\). If a transformation is pursued in the second
  half of this analysis, it will likely be a square root transformation}

\hypertarget{no-relationship}{%
\paragraph{No Relationship}\label{no-relationship}}

\textbf{Age} the mean age of 22 does not vary much across
\textbf{LeagueIndex} such that there is no stark linear relationship.
However, the variance at the highest level seems to be much narrower
than that at the lower levels.

\hypertarget{bimodal}{%
\paragraph{Bimodal}\label{bimodal}}

\textbf{HourPerWeek} has visibly little or no relation to
\textbf{LeagueIndex} 1-4, where \textbf{LeagueIndex} 4-7 seems to have a
visible linear trend resulting in 0.03 vs 0.25. If \textbf{HoursPerWeek}
survives the model trimming, it's bimodality may cause issues with the
model's assumption \(COV(Y)=\sigma^2I\).\textbf{Workersmade,
ComplexUnitsMades, and ComplexAbilityUsed} both have similar differences
between \textbf{LeagueIndex} 1-4 and 4-7 with the portions that have no
relation and a linear relation swapped in comparison to
\textbf{HoursPerWeek}.

\hypertarget{linear}{%
\paragraph{Linear}\label{linear}}

\textbf{TotalHours, MinimapRightClicks, TotalMapExplored, and
UniqueUnitsMade} have a positive linear trend with the response.
\textbf{APM} has a strong linear relationship with the response.

\hypertarget{root}{%
\paragraph{Root}\label{root}}

\textbf{AssignToHotkeys, UniqueHotkeys, and MinimapAttacks} have a
unique square root relationship with the response. This also may cause
issues with the Gaussianity of the model's residuals.

\includegraphics{skillcraft_regression_files/figure-latex/unnamed-chunk-7-1.pdf}
\includegraphics{skillcraft_regression_files/figure-latex/unnamed-chunk-7-2.pdf}
\includegraphics{skillcraft_regression_files/figure-latex/unnamed-chunk-7-3.pdf}

\hypertarget{model-specifications}{%
\section{Model Specifications}\label{model-specifications}}

\hypertarget{multivariant-regression-model-manual-model-iterations-omega-to-omega}{%
\subsection{\texorpdfstring{Multivariant Regression Model Manual Model
Iterations (\(\Omega\) to
\(\omega\))}{Multivariant Regression Model Manual Model Iterations (\textbackslash{}Omega to \textbackslash{}omega)}}\label{multivariant-regression-model-manual-model-iterations-omega-to-omega}}

A model with all predictors will be made. Subsequently, predictors will
be dropped one by one until only predictors with significance of at
least \(\alpha=5\%\) remain starting with \(lm_\Omega\) and ending with
\(lm_\omega\). The results are as follows:

The initial model has many insignificant predictors. The \(lm_\Omega\)
summary:

\begin{longtable}[]{@{}lrrrr@{}}
\caption{Summary of Starting Manual Stepwise Backward Model Selection
\(lm_\Omega\)}\tabularnewline
\toprule
term & estimate & std.error & statistic & p.value\tabularnewline
\midrule
\endfirsthead
\toprule
term & estimate & std.error & statistic & p.value\tabularnewline
\midrule
\endhead
(Intercept) & 1.4609189 & 0.1366369 & 10.6919801 &
0.0000000\tabularnewline
Age & -0.0022911 & 0.0045767 & -0.5005919 & 0.6166916\tabularnewline
HoursPerWeek & 0.0051108 & 0.0016438 & 3.1091408 &
0.0018922\tabularnewline
TotalHours & 0.0001655 & 0.0000228 & 7.2461655 &
0.0000000\tabularnewline
APM & 0.0123241 & 0.0005256 & 23.4484478 & 0.0000000\tabularnewline
AssignToHotkeys & 13.4224183 & 1.2322640 & 10.8924862 &
0.0000000\tabularnewline
UniqueHotkeys & 0.0004731 & 0.0001013 & 4.6709082 &
0.0000031\tabularnewline
MinimapAttacks & 11.1976240 & 1.3853485 & 8.0828932 &
0.0000000\tabularnewline
MinimapRightClicks & -0.7755611 & 0.6249251 & -1.2410465 &
0.2146762\tabularnewline
TotalMapExplored & 0.0059030 & 0.0031347 & 1.8831294 &
0.0597701\tabularnewline
WorkersMade & 2.7112631 & 0.4407556 & 6.1513976 &
0.0000000\tabularnewline
UniqueUnitsMade & 0.0000345 & 0.0001434 & 0.2404174 &
0.8100215\tabularnewline
ComplexUnitsMade & 1.9538597 & 2.5075503 & 0.7791906 &
0.4359229\tabularnewline
ComplexAbilitiesUsed & 1.4388703 & 1.0068550 & 1.4290741 &
0.1530770\tabularnewline
\bottomrule
\end{longtable}

\textbf{Age, UniqueUnitsMade, ComplexUnitsMade, MinimapRightClicks, and
TotalMapExplored} were removed in that order across the model's five
iterations. All remaining predictors were significant to the
predetermined \(\alpha\). The final iteration provided:

\begin{longtable}[]{@{}lrrrr@{}}
\caption{Summary of Final Manual Stepwise Backward Model
Selection\(lm_\omega\)}\tabularnewline
\toprule
term & estimate & std.error & statistic & p.value\tabularnewline
\midrule
\endfirsthead
\toprule
term & estimate & std.error & statistic & p.value\tabularnewline
\midrule
\endhead
(Intercept) & 1.5073472 & 0.0584345 & 25.795485 &
0.0000000\tabularnewline
HoursPerWeek & 0.0052759 & 0.0016259 & 3.244952 &
0.0011863\tabularnewline
TotalHours & 0.0001656 & 0.0000228 & 7.260133 & 0.0000000\tabularnewline
APM & 0.0123335 & 0.0005052 & 24.412493 & 0.0000000\tabularnewline
AssignToHotkeys & 13.5401278 & 1.2312698 & 10.996881 &
0.0000000\tabularnewline
UniqueHotkeys & 0.0005142 & 0.0000988 & 5.202741 &
0.0000002\tabularnewline
MinimapAttacks & 11.1888394 & 1.3551141 & 8.256751 &
0.0000000\tabularnewline
WorkersMade & 2.7573357 & 0.4331283 & 6.366094 &
0.0000000\tabularnewline
ComplexAbilitiesUsed & 2.3408788 & 0.7983207 & 2.932254 &
0.0033881\tabularnewline
\bottomrule
\end{longtable}

\hypertarget{assessing-fit-and-overall-significance}{%
\subsubsection{Assessing Fit and Overall
Significance}\label{assessing-fit-and-overall-significance}}

A test will be performed to see if the predictors provide statistically
significant better model than the null model
\(Y=\overset{\_}{Y}+\epsilon\) where \(Y=LeagueIndex\) . The hypothesis
are as follows:

\[H_o:\beta=0\] \[H_a:LeagueIndex=X\beta+\epsilon\]

Without much surprise using 13 predictor variables results of a very
small p-value of \textasciitilde{}0. Over the iteration, this does not
change notably across the other models as the last model also results in
a p-value \textasciitilde{}0. Thus all \(\Delta p=p_\Omega-p_\omega\)
iterations of the model, we can reject the null hypothesis suggesting
that we should further investigate the explanatory power of our
alternative hypothesis.

\hypertarget{testing-for-significance-between-models}{%
\subsection{Testing for Significance Between
Models}\label{testing-for-significance-between-models}}

If both models had normal residuals, an F-test could be used on
\(lm_\Omega\) and \(lm_\omega\) to determine if the models have
significantly different residuals. \(RSS_\Omega\) and \(RSS_\omega\)
both have Shapiro-Wilk's test statistics that reject the null at
\(\alpha=5\%\) shown in a later section that examines the normality of
each models' residuals. Without gaussian residuals conducting an ANOVA
will be the only practice exercise for the final where the hypothesis is
provided by:

\[ H_o:RSS_\omega = RSS_\Omega\] \[ H_a:RSS_\omega \neq RSS_\Omega\]

Performing an ANOVA test below, we find an insignificant difference in
the models at \(\alpha=5\%\) such that we cannot reject the \(H_o\). The
implications not rejecting \(H_o\) is that regardless of trimming the
predictor space by \(\Delta p\) predictors, \(lm_\omega\) is expected to
produce comparable residuals with a 5\% chance this is a result of the
sampling. Additionally, their \(adjR^2\) is barely different. Where
\(adjR^2_\Omega=\) 0.462 and \(adjR^2_\omega=\) 0.4614. Further analysis
will be conducted to see if the predictive and explanatory power of the
models differs past the magnitude of their residuals.

\begin{longtable}[]{@{}rrrrrr@{}}
\toprule
Res.Df & RSS & Df & Sum of Sq & F & Pr(\textgreater{}F)\tabularnewline
\midrule
\endhead
3322 & 3748.29 & NA & NA & NA & NA\tabularnewline
3327 & 3757.68 & -5 & -9.39 & 1.66 & 0.14\tabularnewline
\bottomrule
\end{longtable}

\hypertarget{confidence-intervals}{%
\subsubsection{Confidence Intervals}\label{confidence-intervals}}

The confidence interval Table\footnote{Delta values are normalized by
  dividing by the mean of the model by related predictors confidence
  interval} show only a few subtleties between models coefficients
confidence intervals.

In the starting model \textbf{Age, MinimapRightClicks, UniqueUnitsMade,
ComplexUnitsMade, and ComplexAbilitiesUsed} are all not significant
based on their p-value, and their confidence intervals straddle 0.
Interestingly enough, \textbf{ComplexAbilitiesUsed} was initially above
the alpha value for significance but made it to the final model. This
could be because of the removal of a confounding variable. The magnitude
of this shift is reflected in its delta value and delta\_width.

For comparison, two summary statistics were added as follows:

\emph{Where:}
\[delta=\frac{(UL_\omega+LL_\omega)-(UL_\Omega+LL_\Omega)}{(UL_\omega+LL_\omega)}=\frac{MeanCI_\omega-MeanCI_\Omega}{MeanCI_\omega}\]
\[delta_{width}=\frac{(UL_\omega-LL_\omega)-(UL_\Omega-LL_\Omega)}{(UL_\omega-LL_\omega)}\]

\begin{longtable}[]{@{}lrrrrrrrr@{}}
\caption{Confidence Intervals Statistics at \(\alpha\)
0.05}\tabularnewline
\toprule
Row.names & LL\_s & UL\_s & LL\_f & UL\_f & mean\_s & mean\_f & delta &
delta\_width\tabularnewline
\midrule
\endfirsthead
\toprule
Row.names & LL\_s & UL\_s & LL\_f & UL\_f & mean\_s & mean\_f & delta &
delta\_width\tabularnewline
\midrule
\endhead
(Intercept) & 1.193 & 1.729 & 1.393 & 1.622 & 1.461 & 1.507 & 0.03 &
-1.34\tabularnewline
Age & -0.011 & 0.007 & NA & NA & -0.002 & NA & NA & NA\tabularnewline
APM & 0.011 & 0.013 & 0.011 & 0.013 & 0.012 & 0.012 & 0.00 &
-0.04\tabularnewline
AssignToHotkeys & 11.006 & 15.838 & 11.126 & 15.954 & 13.422 & 13.540 &
0.01 & 0.00\tabularnewline
ComplexAbilitiesUsed & -0.535 & 3.413 & 0.776 & 3.906 & 1.439 & 2.341 &
0.38 & -0.26\tabularnewline
ComplexUnitsMade & -2.963 & 6.870 & NA & NA & 1.954 & NA & NA &
NA\tabularnewline
HoursPerWeek & 0.002 & 0.008 & 0.002 & 0.008 & 0.005 & 0.005 & 0.03 &
-0.01\tabularnewline
MinimapAttacks & 8.481 & 13.914 & 8.532 & 13.846 & 11.198 & 11.189 &
0.00 & -0.02\tabularnewline
MinimapRightClicks & -2.001 & 0.450 & NA & NA & -0.776 & NA & NA &
NA\tabularnewline
TotalHours & 0.000 & 0.000 & 0.000 & 0.000 & 0.000 & 0.000 & 0.00 &
0.00\tabularnewline
TotalMapExplored & 0.000 & 0.012 & NA & NA & 0.006 & NA & NA &
NA\tabularnewline
UniqueHotkeys & 0.000 & 0.001 & 0.000 & 0.001 & 0.000 & 0.001 & 0.08 &
-0.02\tabularnewline
UniqueUnitsMade & 0.000 & 0.000 & NA & NA & 0.000 & NA & NA &
NA\tabularnewline
WorkersMade & 1.847 & 3.575 & 1.908 & 3.607 & 2.711 & 2.757 & 0.02 &
-0.02\tabularnewline
\bottomrule
\end{longtable}

\hypertarget{confounding}{%
\subsubsection{Confounding}\label{confounding}}

For reference in the following analysis of confounding variables, the
new correlation matrix provides a zoomed view of the target of
discussion.

\includegraphics{skillcraft_regression_files/figure-latex/omegecor-1.pdf}

\hypertarget{complex-unitsabilities}{%
\paragraph{Complex Units/Abilities}\label{complex-unitsabilities}}

As mentioned when exploring the confidence intervals, the notable change
in \textbf{ComplexAbilitiesUsed}'s confidence interval between the
\(lm_\Omega\) to \(lm_\omega\) is likely a result of the removal of the
variable \textbf{ComplexUnitsMade}. Upon reintroducing
\textbf{ComplexUnitsMade} into the final model, we find the following
p-values for both predictors to be insignificant. The difference in
P-value is a warning that we may not distinguish the effects or vary
them independently. This aligns with what is expected based on the
mechanics of the game. Players must make complex units before they can
use their complex abilities.

The way forward with the model is to continue leaving out
\textbf{ComplexUnitsMade} because only making a unit in SC2 is far from
a win condition. Complex units must be utilized with precision and
within the right contexts to reap their full value. On the other hand,
worker units reflected in the predictor \textbf{WorkerUnitsMade} are
units a player may produce and subsequently assign them to indefinite
valued added work. If not interrupted by an attacking force, worker
units will continue to add value to the in-game economy without
additional intervention from the player as long as the resource node is
still abundant.

Furthermore, using complex abilities is generally much more critical
than making these complex units in masses. This also compliments the
initial goal of the modeling to add flavor to APMs in a way that may
reveal what actions are essential and fortunately APM and this
\textbf{ComplexUnitsUsed} these there are mostly orthogonal with cor
0.14.

\begin{longtable}[]{@{}lrrrr@{}}
\caption{ANOVA \(lm_\omega\) and
\(lm_\omega+ComplexUnitsMade\)}\tabularnewline
\toprule
term & estimate & std.error & statistic & p.value\tabularnewline
\midrule
\endfirsthead
\toprule
term & estimate & std.error & statistic & p.value\tabularnewline
\midrule
\endhead
ComplexAbilitiesUsed & 1.560207 & 1.003410 & 1.554905 &
0.1200637\tabularnewline
ComplexUnitsMade & 3.108488 & 2.420861 & 1.284043 &
0.1992165\tabularnewline
\bottomrule
\end{longtable}

\begin{longtable}[]{@{}rrrrrr@{}}
\toprule
Res.Df & RSS & Df & Sum of Sq & F & Pr(\textgreater{}F)\tabularnewline
\midrule
\endhead
3327 & 3757.68 & NA & NA & NA & NA\tabularnewline
3326 & 3755.82 & 1 & 1.86 & 1.65 & 0.2\tabularnewline
\bottomrule
\end{longtable}

\hypertarget{assignttohotkeys-and-actions-per-minute}{%
\paragraph{AssigntToHotkeys and Actions Per
Minute}\label{assignttohotkeys-and-actions-per-minute}}

\textbf{AssignToHotkeys and APM} have the highest correlation within the
final model. \textbf{AssignToHotkeys} was considered to be dropped along
with the PAC related predictors prior. Still, I imagined the predictor
added a significant flavor to what type of actions regardless of its
potential for confounding.\textbf{AssignToHotkeys} in-game is when a
player assigns units or buildings to hotkeys. For example, if the player
has two armies within a match, they may select all of the units in army
one and use the hotkey combination \emph{CTRL+1} to assign those units
to hotkey \emph{1} for future rapid selection. Then the same player can
select their second army use \emph{Ctrl+2} to hotkey \emph{2}. This
works for any commandable unit or building in-game, allowing the player
to reshape hotkeys based as assets are gained or lost.

Both variables will be removed from the model one at a time and then
compared to the final model that contains both. In both subset models'
\textbf{RSS} are statistically significant different. In terms of the
impact to \(adjR^2\), as \textbf{APM} seems to a explain a significant
amount more than \textbf{AssignToHotkeys} as the models have with
\(adjR^2\) of 0.37 and 0.44 compared to the final model 0.46. To
reaffirm the initial effort of dropping predictors that confound heavily
with \textbf{APM} , \textbf{AssignToHotkeys} will be dropped from future
modeling.

\begin{longtable}[]{@{}rrrrrr@{}}
\caption{ANOVA \(lm_\omega\) and \(lm_\omega-APM\)}\tabularnewline
\toprule
Res.Df & RSS & Df & Sum of Sq & F & Pr(\textgreater{}F)\tabularnewline
\midrule
\endfirsthead
\toprule
Res.Df & RSS & Df & Sum of Sq & F & Pr(\textgreater{}F)\tabularnewline
\midrule
\endhead
3327 & 3757.678 & NA & NA & NA & NA\tabularnewline
3328 & 4430.796 & -1 & -673.118 & 595.97 & 0\tabularnewline
\bottomrule
\end{longtable}

\begin{longtable}[]{@{}rrrrrr@{}}
\caption{ANOVA \(lm_\omega\) and
\(lm_\omega-AssignToHotkeys\)}\tabularnewline
\toprule
Res.Df & RSS & Df & Sum of Sq & F & Pr(\textgreater{}F)\tabularnewline
\midrule
\endfirsthead
\toprule
Res.Df & RSS & Df & Sum of Sq & F & Pr(\textgreater{}F)\tabularnewline
\midrule
\endhead
3327 & 3757.678 & NA & NA & NA & NA\tabularnewline
3328 & 3894.264 & -1 & -136.586 & 120.931 & 0\tabularnewline
\bottomrule
\end{longtable}

\hypertarget{hours-metrics}{%
\paragraph{Hours Metrics}\label{hours-metrics}}

Upon closer examination of the remaining predictors its surprising that
\textbf{TotalHours} and \textbf{HoursPerWeek} do not have a higher
correlation. I did not expect both two make it to the final model. This
may have to do with the reporting method. Regardless of the low
correlation it is unclear if not impossible how to vary these two
factors independently.

Both variables will be removed from the model one at a time and then
compared to the final model that contains both. In both subset models'
\textbf{RSS} are statistically significant different. In terms of the
impact to \(adjR^2\), as \textbf{TotalHours} seem to a explain a
significant amount more than \textbf{HoursPerWeek} as the models have
with \(adjR^2\) of 0.45 and 0.46 compared to the final model 0.46.
\textbf{HoursPerWeek} will be dropped for the final model.

\begin{longtable}[]{@{}rrrrrr@{}}
\caption{ANOVA \(lm_\omega\) and
\(lm_\omega-TotalHours\)}\tabularnewline
\toprule
Res.Df & RSS & Df & Sum of Sq & F & Pr(\textgreater{}F)\tabularnewline
\midrule
\endfirsthead
\toprule
Res.Df & RSS & Df & Sum of Sq & F & Pr(\textgreater{}F)\tabularnewline
\midrule
\endhead
3327 & 3757.678 & NA & NA & NA & NA\tabularnewline
3328 & 3817.211 & -1 & -59.533 & 52.71 & 0\tabularnewline
\bottomrule
\end{longtable}

\begin{longtable}[]{@{}rrrrrr@{}}
\caption{ANOVA \(lm_\omega\) and
\(lm_\omega-HoursPerWeek\)}\tabularnewline
\toprule
Res.Df & RSS & Df & Sum of Sq & F & Pr(\textgreater{}F)\tabularnewline
\midrule
\endfirsthead
\toprule
Res.Df & RSS & Df & Sum of Sq & F & Pr(\textgreater{}F)\tabularnewline
\midrule
\endhead
3327 & 3757.678 & NA & NA & NA & NA\tabularnewline
3328 & 3769.571 & -1 & -11.893 & 10.53 & 0.001\tabularnewline
\bottomrule
\end{longtable}

\hypertarget{revised-lm_omega}{%
\paragraph{\texorpdfstring{Revised
\(lm_\omega\)}{Revised lm\_\textbackslash{}omega}}\label{revised-lm_omega}}

After performing the changes for confounding variables, the final model
results in the following coefficients. This model will be rummaged
through more expensively with better tools for the final portion of this
assignment.

\begin{longtable}[]{@{}lrrrr@{}}
\caption{\(lm_\omega\)-HoursPerWeek-AssignToHotkeys}\tabularnewline
\toprule
term & estimate & std.error & statistic & p.value\tabularnewline
\midrule
\endfirsthead
\toprule
term & estimate & std.error & statistic & p.value\tabularnewline
\midrule
\endhead
(Intercept) & 1.6066666 & 0.0573980 & 27.991681 & 0.0e+00\tabularnewline
TotalHours & 0.0001764 & 0.0000228 & 7.743549 & 0.0e+00\tabularnewline
APM & 0.0148680 & 0.0004640 & 32.046258 & 0.0e+00\tabularnewline
UniqueHotkeys & 0.0008002 & 0.0000970 & 8.244981 &
0.0e+00\tabularnewline
MinimapAttacks & 12.5859243 & 1.3761559 & 9.145711 &
0.0e+00\tabularnewline
WorkersMade & 2.6528788 & 0.4410627 & 6.014744 & 0.0e+00\tabularnewline
ComplexAbilitiesUsed & 3.3072502 & 0.8095181 & 4.085456 &
4.5e-05\tabularnewline
\bottomrule
\end{longtable}

\begin{longtable}[]{@{}lrr@{}}
\toprule
& 2.5 \% & 97.5 \%\tabularnewline
\midrule
\endhead
(Intercept) & 1.4941277 & 1.7192055\tabularnewline
TotalHours & 0.0001317 & 0.0002211\tabularnewline
APM & 0.0139584 & 0.0157777\tabularnewline
UniqueHotkeys & 0.0006099 & 0.0009904\tabularnewline
MinimapAttacks & 9.8877272 & 15.2841213\tabularnewline
WorkersMade & 1.7880975 & 3.5176601\tabularnewline
ComplexAbilitiesUsed & 1.7200469 & 4.8944536\tabularnewline
\bottomrule
\end{longtable}

\hypertarget{structural-uncertainty-and-predictions}{%
\subsection{Structural Uncertainty and
Predictions}\label{structural-uncertainty-and-predictions}}

Without using cross-validation, we can see some fundamental issues with
the fitted values of each model reviewed. The predictions of the model
behavior and accuracy comparable between \(\Omega\) \& \(\omega\), so
only \(\omega\) will be used in the following section.

The first plot is a scatterplot with the fitted values by dominant
predictor APM. Some of the players are excepted to have a LeagueIndex
\textgreater{} 10, which does not exist in sampled response. Although
LeagueIndex \textgreater{} 7 does tease that the Grandmaster tier is an
unbounded tier in terms of skill points. Overall, the continuous fitted
values fail to capture the discrete nature of the response.

The fitted values will be flattened such that when LeagueIndex
\textgreater{} 7 will be set LeagueIndex=7, then each value will be
rounded, so only integer values remain to help interpret the results of
the model.

\includegraphics{skillcraft_regression_files/figure-latex/unnamed-chunk-18-1.pdf}

To assess the predictive accuracy of the model the flattened and rounded
values fitted values are then compared to the sampled values overall
providing a 34\% accuracy. This is a very low accuracy considering 100\%
of the data was used to train the model. The correct \% by
\textbf{LeagueIndex} is plotted below accompanied by a base rate \% that
reflects the chance of guessing the correct \textbf{LeagueIndex} using:
\[BaseRate\%=n_{LeagueIndex=i}/n_{total}\].

\begin{verbatim}
## `summarise()` ungrouping output (override with `.groups` argument)
\end{verbatim}

\includegraphics{skillcraft_regression_files/figure-latex/unnamed-chunk-19-1.pdf}

Another part of the models bias is that it does not place anyone below
\textbf{LeagueIndex=} 2. The behavior of the ordinal response severely
limits the predictive power of this model. The model has infinite more
likelihood of predicting someone as \textbf{LeagueIndex} = 4 who is
actually \textbf{LeagueIndex}=4 then predicting someone in
\textbf{LeagueIndex}=1 who is actually \textbf{LeagueIndex}=1. Less
severe lopsidedness can be seen through the varying
\textbf{LeagueIndexs' Correct \%}. Specifically, \textbf{Correct \%} for
\textbf{LeagueIndex} 3 to 7 perform much better than the base rate.
These sign shows are the predictive power is heavily biased towards
higher \textbf{LeagueIndex}

\hypertarget{conclusion}{%
\subsection{Conclusion}\label{conclusion}}

\hypertarget{researchs-explanatory-power}{%
\subsubsection{Research's Explanatory
Power}\label{researchs-explanatory-power}}

The initial goal was to add some flavor to \textbf{APM} concerning what
makes players highly ranked. Due to structure issues, this model overall
performs very poorly. As a result, it needs to be kept in mind that the
following predictors explain less than half the variation observed in
the response.

From this analysis, we can see that the amount in terms of
\textbf{TotalHours} a player dedicates seems to a significant predictor,
which is a good sign for players willing to invest time into their
craft. The suggested rate of progress is a bit disheartening as we
expected the mean response of \textbf{LeagueIndex} to increase by 1 per
5000 \textbf{TotalHours}.

Using the predictor \textbf{WorkersMade}, one worker every 2.65 seconds
is expected to increase mean LeagueIndex by one. Workers drive a
player's economy, and the professionals always seems to have them in
enormous quantities.

One minimap attack per 12.6 seconds is expected to increase mean
\textbf{LeagueIndex} by one. Minimap attacks save the player from
changing their main view for each attack command by allowing them to
command a unit to any point using the minimap. For example, suppose we
used the hotkey assignments mentioned previously. In that case, a player
could press \emph{1} and attack-click somewhere on the minimap to
command an entire army to attack a location without changing the
player's field of view. In a match where there are skirmishes across the
map, a player more skilled at minimap attacks would be expected to have
a strong advantage in managing multiple battlefronts near
simultaneously. This may be a good target skill for players trying to
increase their \textbf{LeagueIndex}.

One complex ability used per 3.3 seconds is expected to increase mean
\textbf{LeagueIndex} by one. Even without the confounding variable in
this model, it is still difficult to translate this idea into in-game
practice because these Complex units need to be made before their
abilities can be used. To construct these used, a player needs to have a
relatively strong economy that may not be obtainable until midmatch.

It would take 1250 unique hotkeys used per second to increase mean
\textbf{LeagueIndex} by one. This variable's units are incorrect or the
effect is feeble. No additional information was provided by the data
source to further troubleshoot (``UCI Machine Learning Repository:
SkillCraft1 Master Table Dataset Data Set'' n.d.).

Finally, \textbf{APM} increases \textbf{LeagueIndex} by one per 68. It's
not surprising that speed seems to have a dominating effect.

\hypertarget{prelude-to-final}{%
\subsubsection{Prelude to final}\label{prelude-to-final}}

For the final, the logistical regression will remodel the same problem
with a different set of techniques and assumptions that fit the ordinal
response. The second iteration is likely to be much smoother because of
this exploratory analysis's heavy leg work.

-- End Midterm 2 --

\hypertarget{transition-to-the-final}{%
\section{Transition to the Final}\label{transition-to-the-final}}

There are five things that will be completed to fulfill the final
portion of this paper, they are as follows:

\hypertarget{portional-odds-model}{%
\subsection{Portional Odds model}\label{portional-odds-model}}

Construct a ordinal regression model using the the \texttt{Mass} package
and function \texttt{polr}where \(-\beta=\eta\) using the same
parameters as final model \(lm_\omega\):
\[log(\frac{p}{1-p})=\alpha+\eta_1x_1+\eta_2x_2...+\eta_px_p\\ vs. \\log(\frac{p_i}{1-p_i})=\alpha_i+\eta_1x_1+\eta_2x_2...+\eta_px_p\]
Logistic regression predicts \(p\),the probability a binomial response,
alternatively ordinal regression predicts \(p_i\) the predictors
ceoffients partitioned by multinominal response \(i \in LeagueIndex\).
This encoding predicts the logit odds based on a set of parameters
\(X\).

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{require}\NormalTok{(foreign)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Loading required package: foreign
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{require}\NormalTok{(ggplot2)}
\KeywordTok{require}\NormalTok{(MASS)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Loading required package: MASS
\end{verbatim}

\begin{verbatim}
## 
## Attaching package: 'MASS'
\end{verbatim}

\begin{verbatim}
## The following object is masked from 'package:dplyr':
## 
##     select
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{require}\NormalTok{(Hmisc)}
\KeywordTok{require}\NormalTok{(reshape2)}

\NormalTok{m <-}\StringTok{ }\KeywordTok{polr}\NormalTok{(}\KeywordTok{factor}\NormalTok{(LeagueIndex) }\OperatorTok{~}\StringTok{ }\NormalTok{APM }\OperatorTok{+}\StringTok{ }\NormalTok{TotalHours, }\DataTypeTok{data =}\NormalTok{ sc, }\DataTypeTok{Hess=}\OtherTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ctable <-}\StringTok{ }\KeywordTok{coef}\NormalTok{(}\KeywordTok{summary}\NormalTok{(m))}
\CommentTok{## calculate and store p values}
\NormalTok{p <-}\StringTok{ }\KeywordTok{pnorm}\NormalTok{(}\KeywordTok{abs}\NormalTok{(ctable[, }\StringTok{"t value"}\NormalTok{]), }\DataTypeTok{lower.tail =} \OtherTok{FALSE}\NormalTok{) }\OperatorTok{*}\StringTok{ }\DecValTok{2}
\CommentTok{## combined table}
\NormalTok{ctable <-}\StringTok{ }\KeywordTok{cbind}\NormalTok{(ctable, }\StringTok{"p value"}\NormalTok{ =}\StringTok{ }\NormalTok{p)}

\NormalTok{ci <-}\StringTok{ }\KeywordTok{exp}\NormalTok{(}\KeywordTok{confint}\NormalTok{(m)) }\CommentTok{# default method gives profiled CIs}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Waiting for profiling to be done...
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{co <-}\KeywordTok{exp}\NormalTok{(}\KeywordTok{coef}\NormalTok{(m))}
\NormalTok{c<-}\KeywordTok{round}\NormalTok{(}\KeywordTok{cbind}\NormalTok{(ci,}\DataTypeTok{Nominal=}\NormalTok{co),}\DecValTok{3}\NormalTok{)}

\KeywordTok{kable}\NormalTok{(ctable,}\DataTypeTok{format =} \StringTok{"markdown"}\NormalTok{, }\DataTypeTok{digits =} \DecValTok{4}\NormalTok{, }\DataTypeTok{caption=}\StringTok{"Ordinal Model"}\NormalTok{ )}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}lrrrr@{}}
\caption{Ordinal Model}\tabularnewline
\toprule
& Value & Std. Error & t value & p value\tabularnewline
\midrule
\endfirsthead
\toprule
& Value & Std. Error & t value & p value\tabularnewline
\midrule
\endhead
APM & 0.0307 & 0.0009 & 33.7002 & 0.0000\tabularnewline
TotalHours & 0.0008 & 0.0001 & 12.1164 & 0.0000\tabularnewline
1\textbar{}2 & 0.1529 & 0.1097 & 1.3940 & 0.1633\tabularnewline
2\textbar{}3 & 1.6048 & 0.0956 & 16.7790 & 0.0000\tabularnewline
3\textbar{}4 & 2.8441 & 0.0995 & 28.5892 & 0.0000\tabularnewline
4\textbar{}5 & 4.2950 & 0.1127 & 38.1056 & 0.0000\tabularnewline
5\textbar{}6 & 6.0066 & 0.1342 & 44.7461 & 0.0000\tabularnewline
6\textbar{}7 & 10.1836 & 0.2626 & 38.7769 & 0.0000\tabularnewline
\bottomrule
\end{longtable}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{kable}\NormalTok{(c,}\DataTypeTok{caption=}\StringTok{"Exp. Confidence Intervals"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}lrrr@{}}
\caption{Exp. Confidence Intervals}\tabularnewline
\toprule
& 2.5 \% & 97.5 \% & Nominal\tabularnewline
\midrule
\endfirsthead
\toprule
& 2.5 \% & 97.5 \% & Nominal\tabularnewline
\midrule
\endhead
APM & 1.029 & 1.033 & 1.031\tabularnewline
TotalHours & 1.001 & 1.001 & 1.001\tabularnewline
\bottomrule
\end{longtable}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#https://stats.idre.ucla.edu/r/dae/ordinal-logistic-regression/}
\CommentTok{#The intercept term shows cumulative odds}
\CommentTok{#melt, group by , summarize}
\end{Highlighting}
\end{Shaded}

To generate bias P-Values a z-test is used where the t-value is compared
with the standard normal distribution. These p-values have decreasing
bias as sample size increases and considering \$n=\$3336 the bias should
be reasonably diminished producing subtlety asymmetric confidence
intervals.

\hypertarget{apm-in-the-ordinal-model}{%
\subsubsection{APM in the ordinal
model}\label{apm-in-the-ordinal-model}}

For Starcraft II players this ranked season, for everyone one unit
increase in players APM the odds of being ranked plat below is decrease
3.3\% holding all other variables constant.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{#pc<-sc%>%group_by(LeagueIndex)%>%summarize(AvgAPM=mean(APM))}
\end{Highlighting}
\end{Shaded}

\hypertarget{mlr-vs-proportional-odds-model-shallow-dive}{%
\subsection{MLR vs Proportional Odds Model (shallow
dive)}\label{mlr-vs-proportional-odds-model-shallow-dive}}

\begin{itemize}
\tightlist
\item
  Briefly Compare the previous model and new models power using the same
  predictors, because the following models analyzed may not be a subset
  of one another.
\item
  Revisit model specifications with a step wise reg focused on BIC
\item
  Perform diagnostics

  \begin{itemize}
  \tightlist
  \item
    Adjust for outliers, and iterate
  \item
    Perform diagnostics for portional odds, and iterate
  \end{itemize}
\item
  Predict
\end{itemize}

** OR **

\begin{itemize}
\tightlist
\item
  Perform diagnostics

  \begin{itemize}
  \tightlist
  \item
    Adjust for outliers, and iterate
  \item
    Perform diagnostics on the residuals, and iterate
  \end{itemize}
\item
  Construct a initial ordinal regression model with the same predictors
  as \(lm_\omega\).
\item
  Briefly Compare the previous model and new models power using the same
  predictors, because the following models analyzed may not be a subset
  of one another.
\item
  Revisit model specifications with a step wise reg focused on BIC
\item
  Assess porional odds assumptions

  \begin{itemize}
  \tightlist
  \item
    ``One of the assumptions underlying ordinal logistic (and ordinal
    probit) regression is that the relationship between each pair of
    outcome groups is the same. In other words, ordinal logistic
    regression assumes that the coefficients that describe the
    relationship between, say, the lowest versus all higher categories
    of the response variable are the same as those that describe the
    relationship between the next lowest category and all higher
    categories, etc. This is called the proportional odds assumption or
    the parallel regression assumption. Because the relationship between
    all pairs of groups is the same, there is only one set of
    coefficients.''
  \end{itemize}
\end{itemize}

\hypertarget{appendix}{%
\section{Appendix}\label{appendix}}

\hypertarget{about-columns}{%
\subsubsection{About Columns}\label{about-columns}}

\textbf{Attribute Information (``UCI Machine Learning Repository:
SkillCraft1 Master Table Dataset Data Set'' n.d.) :}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  GameID: Unique ID number for each game (integer)
\item
  LeagueIndex: Bronze, Silver, Gold, Platinum, Diamond, Master,
  GrandMaster, and Professional leagues coded 1-8 (Ordinal)
\item
  Age: Age of each player (integer)
\item
  HoursPerWeek: Reported hours spent playing per week (integer)
\item
  TotalHours: Reported total hours spent playing (integer)
\item
  APM: Action per minute (continuous)
\item
  SelectByHotkeys: Number of unit or building selections made using
  hotkeys per timestamp (continuous)
\item
  AssignToHotkeys: Number of units or buildings assigned to hotkeys per
  timestamp (continuous)
\item
  UniqueHotkeys: Number of unique hotkeys used per timestamp
  (continuous)
\item
  MinimapAttacks: Number of attack actions on minimap per timestamp
  (continuous)
\item
  MinimapRightClicks: number of right-clicks on minimap per timestamp
  (continuous)
\item
  NumberOfPACs: Number of PACs per timestamp (continuous)
\item
  GapBetweenPACs: Mean duration in milliseconds between PACs
  (continuous)
\item
  ActionLatency: Mean latency from the onset of a PACs to their first
  action in milliseconds (continuous)
\item
  ActionsInPAC: Mean number of actions within each PAC (continuous)
\item
  TotalMapExplored: The number of 24x24 game coordinate grids viewed by
  the player per timestamp (continuous)
\item
  WorkersMade: Number of SCVs, drones, and probes trained per timestamp
  (continuous)
\item
  UniqueUnitsMade: Unique unites made per timestamp (continuous)
\item
  ComplexUnitsMade: Number of ghosts, infestors, and high templars
  trained per timestamp (continuous)
\item
  ComplexAbilitiesUsed: Abilities requiring specific targeting
  instructions used per timestamp (continuous)
\end{enumerate}

\hypertarget{why-violin-plots.}{%
\subsubsection{Why Violin Plots.}\label{why-violin-plots.}}

I decided to use Violin plots because I found with less tweaking they
provided almost all the information I was looking for compared to
scatter plots. Head to head a limitation of violin plots is that they
make it seems as though the LeagueIndex level size contains the same
\(n\). The histogram earlier in this analysis shows clearly that \(n\)
at each level of the \textbf{LeagueIndex} is not equal so choosing a
tool on the basis of reiterating that point seems redundant. The benefit
of Violin plots is that they provide a smoothed density plot at each
\textbf{LeagueIndex} with a single point that represents the mean. This
same thing could be done with scatter plots but I found it took much
more staring and plot to plot variation.

The following is some head to head varieties plotting the data.

\hypertarget{code}{%
\section{Code}\label{code}}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(tidyverse)}
\KeywordTok{library}\NormalTok{(dbplyr) }\CommentTok{#piping}
\KeywordTok{library}\NormalTok{(ggplot2) }\CommentTok{#plotting}
\KeywordTok{library}\NormalTok{(gridExtra)}\CommentTok{# easy plot grids}
\KeywordTok{library}\NormalTok{(Hmisc) }\CommentTok{# for correlation matrix}
\KeywordTok{library}\NormalTok{(corrplot) }\CommentTok{# For correlation matrix graphic}
\KeywordTok{library}\NormalTok{(broom) }\CommentTok{#tidy lm summaries}
\KeywordTok{library}\NormalTok{(knitr) }\CommentTok{#pretty tables}
\KeywordTok{library}\NormalTok{(reshape2) }\CommentTok{#melt function}

\NormalTok{sc<-}\KeywordTok{read_csv}\NormalTok{(}\StringTok{"~/STAT757/skillcraft/SkillCraft1_Dataset.csv"}\NormalTok{)}

\KeywordTok{colnames}\NormalTok{(sc)}

\NormalTok{cbPalette <-}\StringTok{ }\KeywordTok{c}\NormalTok{(}\StringTok{"#CC6600"}\NormalTok{, }\StringTok{"#999999"}\NormalTok{, }\StringTok{"#FFCC00"}\NormalTok{, }\StringTok{"#CCCFFF"}\NormalTok{, }\StringTok{"#CCFFFF"}\NormalTok{,}\StringTok{"#0072B2"}\NormalTok{, }\StringTok{"#FF6600"}\NormalTok{)}

\CommentTok{#set type}
\NormalTok{sc}\OperatorTok{$}\NormalTok{HoursPerWeek<-}\KeywordTok{as.numeric}\NormalTok{(sc}\OperatorTok{$}\NormalTok{HoursPerWeek)}
\NormalTok{sc}\OperatorTok{$}\NormalTok{TotalHours<-}\KeywordTok{as.numeric}\NormalTok{(sc}\OperatorTok{$}\NormalTok{TotalHours)}

\NormalTok{count_missing_age<-}\KeywordTok{count}\NormalTok{(sc}\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(}\KeywordTok{is.na}\NormalTok{(Age))}\OperatorTok{%>%}\KeywordTok{arrange}\NormalTok{(LeagueIndex))}
\NormalTok{count_professional<-}\KeywordTok{count}\NormalTok{(sc}\OperatorTok{%>%}\KeywordTok{filter}\NormalTok{(LeagueIndex}\OperatorTok{==}\DecValTok{8}\NormalTok{))}
\NormalTok{count_grandmaster<-}\KeywordTok{count}\NormalTok{(sc}\OperatorTok{%>%}\KeywordTok{filter}\NormalTok{(LeagueIndex}\OperatorTok{==}\DecValTok{8}\NormalTok{))}
\KeywordTok{print}\NormalTok{(}\KeywordTok{paste}\NormalTok{(}\StringTok{'There are '}\NormalTok{,count_missing_age,}\StringTok{' missing values in the age column. There are '}\NormalTok{,count_professional,}\StringTok{' professional #players.'}\NormalTok{))}

\NormalTok{sc<-}\KeywordTok{filter}\NormalTok{(sc,sc}\OperatorTok{$}\NormalTok{TotalHours}\OperatorTok{<}\DecValTok{1000000}\NormalTok{)}

\NormalTok{sc<-sc}\OperatorTok{%>%}
\StringTok{  }\KeywordTok{drop_na}\NormalTok{()}\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(HoursPerWeek}\OperatorTok{!=}\DecValTok{0}\NormalTok{)}
\NormalTok{sc_describe<-}\KeywordTok{describe}\NormalTok{(sc)}

\NormalTok{sc<-sc}\OperatorTok{%>%}
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{NumberOfPACs=}\NormalTok{NumberOfPACs}\OperatorTok{*}\FloatTok{88.5}\NormalTok{,}
         \DataTypeTok{MinimapAttacks=}\NormalTok{MinimapAttacks}\OperatorTok{*}\FloatTok{88.5}\NormalTok{,}
         \DataTypeTok{MinimapRightClicks=}\NormalTok{MinimapRightClicks}\OperatorTok{*}\FloatTok{88.5}\NormalTok{,}
         \DataTypeTok{SelectByHotkeys=}\NormalTok{SelectByHotkeys}\OperatorTok{*}\FloatTok{88.5}\NormalTok{,}
         \DataTypeTok{AssignToHotkeys=}\NormalTok{AssignToHotkeys}\OperatorTok{*}\FloatTok{88.5}\NormalTok{,}
         \DataTypeTok{UniqueHotkeys=}\NormalTok{UniqueHotkeys}\OperatorTok{*}\FloatTok{88.5}\NormalTok{,}
         \DataTypeTok{WorkersMade=}\NormalTok{WorkersMade}\OperatorTok{*}\FloatTok{88.5}\NormalTok{,}
         \DataTypeTok{UniqueUnitsMade=}\NormalTok{UniqueUnitsMade}\OperatorTok{*}\FloatTok{88.5}\NormalTok{,}
         \DataTypeTok{ComplexUnitsMade=}\NormalTok{ComplexUnitsMade}\OperatorTok{*}\FloatTok{88.5}\NormalTok{,}
         \DataTypeTok{ComplexAbilitiesUsed=}\NormalTok{ComplexAbilitiesUsed}\OperatorTok{*}\FloatTok{88.5}\NormalTok{,}
         \DataTypeTok{GapBetweenPACs=}\NormalTok{GapBetweenPACs}\OperatorTok{*}\DecValTok{1000}\NormalTok{,}
         \DataTypeTok{ActionLatency=}\NormalTok{ActionLatency}\OperatorTok{*}\DecValTok{1000}\NormalTok{)}


\NormalTok{LeagueIndex_Normal<-}\KeywordTok{shapiro.test}\NormalTok{(sc}\OperatorTok{$}\NormalTok{LeagueIndex)}
  
\KeywordTok{ggplot}\NormalTok{(sc)}\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_histogram}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{LeagueIndex,}\DataTypeTok{y=}\NormalTok{(..count..)}\OperatorTok{/}\KeywordTok{sum}\NormalTok{(..count..),}\DataTypeTok{fill=}\NormalTok{LeagueIndex),}
      \DataTypeTok{position =} \StringTok{"identity"}\NormalTok{, }\DataTypeTok{binwidth =} \DecValTok{1}\NormalTok{,}\DataTypeTok{fill=}\NormalTok{cbPalette) }\OperatorTok{+}
\StringTok{  }\KeywordTok{ylab}\NormalTok{(}\StringTok{"Relative Frequency"}\NormalTok{)}\OperatorTok{+}
\StringTok{  }\KeywordTok{ggtitle}\NormalTok{(}\StringTok{'LeagueIndex Distribution'}\NormalTok{,}\DataTypeTok{subtitle =} \KeywordTok{paste}\NormalTok{(LeagueIndex_Normal[}\DecValTok{3}\NormalTok{],}
      \StringTok{" P-Value: "}\NormalTok{,LeagueIndex_Normal[}\DecValTok{2}\NormalTok{]))}\OperatorTok{+}\KeywordTok{xlab}\NormalTok{(}\StringTok{"LeagueIndex 1-Bronze to 7-Grandmaster"}\NormalTok{)}\OperatorTok{+}\KeywordTok{theme_classic}\NormalTok{()}

\NormalTok{sc_cor<-}\KeywordTok{cor}\NormalTok{(}\KeywordTok{select_if}\NormalTok{(sc,is.numeric),}\DataTypeTok{use =} \StringTok{"complete.obs"}\NormalTok{)}
\NormalTok{sc_cor_plot<-}\KeywordTok{corrplot}\NormalTok{(sc_cor,}
    \DataTypeTok{tl.cex=}\NormalTok{.}\DecValTok{75}\NormalTok{,}
    \DataTypeTok{tl.col=}\StringTok{'black'}\NormalTok{,}
    \DataTypeTok{type=}\StringTok{"lower"}\NormalTok{,)}

\NormalTok{sc<-sc}\OperatorTok{%>%}\KeywordTok{select}\NormalTok{(}\OperatorTok{!}\KeywordTok{c}\NormalTok{(GameID,ActionLatency,GapBetweenPACs,NumberOfPACs,SelectByHotkeys,ActionsInPAC))}

\NormalTok{cor_hoursperweek<-}\KeywordTok{paste}\NormalTok{(}
  \KeywordTok{round}\NormalTok{(}\KeywordTok{cor}\NormalTok{(sc}\OperatorTok{%>%}\KeywordTok{filter}\NormalTok{(}\KeywordTok{between}\NormalTok{(LeagueIndex,}\DecValTok{1}\NormalTok{,}\DecValTok{4}\NormalTok{))}\OperatorTok{%>%}\KeywordTok{select}\NormalTok{(LeagueIndex),}
\NormalTok{    sc}\OperatorTok{%>%}\KeywordTok{filter}\NormalTok{(}\KeywordTok{between}\NormalTok{(LeagueIndex,}\DecValTok{1}\NormalTok{,}\DecValTok{4}\NormalTok{))}\OperatorTok{%>%}\KeywordTok{select}\NormalTok{(HoursPerWeek))[}\DecValTok{1}\NormalTok{],}
    \DecValTok{2}\NormalTok{),}
  \StringTok{"vs"}\NormalTok{,}
  \KeywordTok{round}\NormalTok{(}\KeywordTok{cor}\NormalTok{(sc}\OperatorTok{%>%}\KeywordTok{filter}\NormalTok{(}\KeywordTok{between}\NormalTok{(LeagueIndex,}\DecValTok{4}\NormalTok{,}\DecValTok{7}\NormalTok{))}\OperatorTok{%>%}\KeywordTok{select}\NormalTok{(LeagueIndex),}
\NormalTok{    sc}\OperatorTok{%>%}\KeywordTok{filter}\NormalTok{(}\KeywordTok{between}\NormalTok{(LeagueIndex,}\DecValTok{4}\NormalTok{,}\DecValTok{7}\NormalTok{))}\OperatorTok{%>%}\KeywordTok{select}\NormalTok{(HoursPerWeek))[}\DecValTok{1}\NormalTok{],}
    \DecValTok{2}\NormalTok{)}
\NormalTok{)}

\NormalTok{VioLeagueIndex<-}\ControlFlowTok{function}\NormalTok{(predictor)\{}
  \KeywordTok{ggplot}\NormalTok{(sc, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\KeywordTok{factor}\NormalTok{(LeagueIndex), }\DataTypeTok{y=}\KeywordTok{unlist}\NormalTok{(sc}\OperatorTok{%>%}\KeywordTok{select}\NormalTok{(}\KeywordTok{all_of}\NormalTok{(predictor))), }\DataTypeTok{fill=}\KeywordTok{factor}\NormalTok{(LeagueIndex))) }\OperatorTok{+}\StringTok{ }
\StringTok{    }\KeywordTok{geom_violin}\NormalTok{(}\DataTypeTok{trim=}\OtherTok{FALSE}\NormalTok{, }\DataTypeTok{color=}\StringTok{"black"}\NormalTok{)}\OperatorTok{+}\KeywordTok{scale_fill_manual}\NormalTok{(}\DataTypeTok{values=}\NormalTok{cbPalette)}\OperatorTok{+}
\StringTok{    }\KeywordTok{stat_summary}\NormalTok{(}\DataTypeTok{fun.data=}\NormalTok{mean_sdl,}\DataTypeTok{geom=}\StringTok{"pointrange"}\NormalTok{, }\DataTypeTok{color=}\StringTok{"black"}\NormalTok{)}\OperatorTok{+}\StringTok{ }\KeywordTok{coord_flip}\NormalTok{()}\OperatorTok{+}
\StringTok{    }\KeywordTok{ggtitle}\NormalTok{(}\KeywordTok{paste}\NormalTok{(}\StringTok{"LeagueIndex by"}\NormalTok{,predictor))}\OperatorTok{+}
\StringTok{    }\KeywordTok{xlab}\NormalTok{(}\StringTok{"LeagueIndex"}\NormalTok{)}\OperatorTok{+}\KeywordTok{ylab}\NormalTok{(predictor) }\OperatorTok{+}\StringTok{ }\KeywordTok{guides}\NormalTok{(}\DataTypeTok{fill=} \OtherTok{FALSE}\NormalTok{)}\OperatorTok{+}\KeywordTok{theme_classic}\NormalTok{()}
\NormalTok{    \}}

\NormalTok{plots<-}\KeywordTok{lapply}\NormalTok{(}\KeywordTok{colnames}\NormalTok{(sc)[}\DecValTok{2}\OperatorTok{:}\KeywordTok{length}\NormalTok{(}\KeywordTok{colnames}\NormalTok{(sc))],VioLeagueIndex)}

\KeywordTok{do.call}\NormalTok{(}\StringTok{"grid.arrange"}\NormalTok{, }\KeywordTok{c}\NormalTok{(plots[}\DecValTok{1}\OperatorTok{:}\DecValTok{4}\NormalTok{], }\DataTypeTok{ncol=}\DecValTok{2}\NormalTok{))}
\KeywordTok{do.call}\NormalTok{(}\StringTok{"grid.arrange"}\NormalTok{, }\KeywordTok{c}\NormalTok{(plots[}\DecValTok{5}\OperatorTok{:}\DecValTok{8}\NormalTok{], }\DataTypeTok{ncol=}\DecValTok{2}\NormalTok{))}
\KeywordTok{do.call}\NormalTok{(}\StringTok{"grid.arrange"}\NormalTok{, }\KeywordTok{c}\NormalTok{(plots[}\DecValTok{9}\OperatorTok{:}\DecValTok{13}\NormalTok{], }\DataTypeTok{ncol=}\DecValTok{2}\NormalTok{))}

\NormalTok{sc_lm<-}\KeywordTok{lm}\NormalTok{(LeagueIndex}\OperatorTok{~}\NormalTok{.,sc)}
\NormalTok{sc_lm_}\DecValTok{1}\NormalTok{<-}\KeywordTok{update}\NormalTok{(sc_lm,.}\OperatorTok{~}\NormalTok{.}\OperatorTok{-}\NormalTok{UniqueUnitsMade ,sc)}
\NormalTok{sc_lm_}\DecValTok{2}\NormalTok{<-}\KeywordTok{update}\NormalTok{(sc_lm,.}\OperatorTok{~}\NormalTok{.}\OperatorTok{-}\NormalTok{Age}\OperatorTok{-}\NormalTok{UniqueUnitsMade)}
\NormalTok{sc_lm_}\DecValTok{3}\NormalTok{<-}\KeywordTok{update}\NormalTok{(sc_lm,.}\OperatorTok{~}\NormalTok{.}\OperatorTok{-}\NormalTok{Age}\OperatorTok{-}\NormalTok{UniqueUnitsMade}\OperatorTok{-}\NormalTok{ComplexUnitsMade)}
\NormalTok{sc_lm_}\DecValTok{4}\NormalTok{<-}\KeywordTok{update}\NormalTok{(sc_lm,.}\OperatorTok{~}\NormalTok{.}\OperatorTok{-}\NormalTok{Age}\OperatorTok{-}\NormalTok{UniqueUnitsMade}\OperatorTok{-}\NormalTok{ComplexUnitsMade}\OperatorTok{-}\NormalTok{MinimapRightClicks)}
\NormalTok{sc_lm_final<-}\KeywordTok{update}\NormalTok{(sc_lm,.}\OperatorTok{~}\NormalTok{.}\OperatorTok{-}\NormalTok{Age}\OperatorTok{-}\NormalTok{TotalMapExplored}\OperatorTok{-}\NormalTok{UniqueUnitsMade}\OperatorTok{-}\NormalTok{MinimapRightClicks}\OperatorTok{-}\NormalTok{ComplexUnitsMade)}

\KeywordTok{kable}\NormalTok{(}\KeywordTok{anova}\NormalTok{(sc_lm,sc_lm_final),}\DataTypeTok{digits=}\DecValTok{2}\NormalTok{)}

\CommentTok{#t<-data.frame(confint(sc_lm),confint(sc_lm_final))}
\NormalTok{t1 <-}\StringTok{ }\KeywordTok{data.frame}\NormalTok{(}\KeywordTok{confint}\NormalTok{(sc_lm))}
\NormalTok{t2 <-}\StringTok{ }\KeywordTok{data.frame}\NormalTok{(}\KeywordTok{confint}\NormalTok{(sc_lm_final))}
\NormalTok{t3<-}\KeywordTok{merge}\NormalTok{(t1,t2,}\DataTypeTok{by=}\StringTok{"row.names"}\NormalTok{,}\DataTypeTok{all=}\OtherTok{TRUE}\NormalTok{)}
\NormalTok{t3<-t3}\OperatorTok{%>%}\KeywordTok{rename}\NormalTok{(}\DataTypeTok{LL_s=}\NormalTok{X2.}\DecValTok{5}\NormalTok{...x,}\DataTypeTok{UL_s=}\NormalTok{X97.}\DecValTok{5}\NormalTok{...x,}\DataTypeTok{LL_f=}\NormalTok{X2.}\DecValTok{5}\NormalTok{...y,}\DataTypeTok{UL_f=}\NormalTok{X97.}\DecValTok{5}\NormalTok{...y)}
\NormalTok{t3<-t3}\OperatorTok{%>%}\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{mean_s=}\NormalTok{(UL_s}\OperatorTok{+}\NormalTok{LL_s)}\OperatorTok{/}\DecValTok{2}\NormalTok{,}
                \DataTypeTok{mean_f=}\NormalTok{(UL_f}\OperatorTok{+}\NormalTok{LL_f)}\OperatorTok{/}\DecValTok{2}\NormalTok{,}
                \DataTypeTok{delta=}\NormalTok{(mean_f}\OperatorTok{-}\NormalTok{mean_s)}\OperatorTok{/}\NormalTok{mean_f,}
                \DataTypeTok{delta_width=}\NormalTok{((UL_f}\OperatorTok{-}\NormalTok{LL_f)}\OperatorTok{-}\NormalTok{(UL_s}\OperatorTok{-}\NormalTok{LL_s))}\OperatorTok{/}\NormalTok{(UL_f}\OperatorTok{-}\NormalTok{LL_f))}\OperatorTok{%>%}
\StringTok{         }\KeywordTok{mutate_if}\NormalTok{(is.numeric, }\OperatorTok{~}\KeywordTok{round}\NormalTok{(., }\DecValTok{3}\NormalTok{))}
\KeywordTok{kable}\NormalTok{(t3,}\DataTypeTok{format =} \StringTok{"markdown"}\NormalTok{, }\DataTypeTok{digits =} \KeywordTok{c}\NormalTok{(}\DecValTok{4}\NormalTok{,}\DecValTok{4}\NormalTok{,}\DecValTok{4}\NormalTok{,}\DecValTok{4}\NormalTok{,}\DecValTok{4}\NormalTok{,}\DecValTok{4}\NormalTok{,}\DecValTok{4}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{2}\NormalTok{), }\DataTypeTok{caption=}\StringTok{"Confidence Intervals Statistics at $}\CharTok{\textbackslash{}\textbackslash{}}\StringTok{alpha$ 0.05"}\NormalTok{ )}

\NormalTok{sc_omega<-sc}\OperatorTok{%>%}\KeywordTok{select}\NormalTok{(HoursPerWeek,TotalHours,HoursPerWeek,APM,AssignToHotkeys,WorkersMade,ComplexUnitsMade,ComplexAbilitiesUsed)}

\NormalTok{sc_omega_cor<-}\KeywordTok{cor}\NormalTok{(}\KeywordTok{select_if}\NormalTok{(sc_omega,is.numeric),}\DataTypeTok{use =} \StringTok{"complete.obs"}\NormalTok{)}
\NormalTok{sc_omega_cor_plot<-}\KeywordTok{corrplot}\NormalTok{(sc_omega_cor,}
    \DataTypeTok{tl.cex=}\NormalTok{.}\DecValTok{75}\NormalTok{,}
    \DataTypeTok{tl.col=}\StringTok{'black'}\NormalTok{,}
    \DataTypeTok{method=}\StringTok{"number"}\NormalTok{,}
    \DataTypeTok{type=}\StringTok{"lower"}\NormalTok{)}

\NormalTok{sc_lm_}\DecValTok{5}\NormalTok{<-}\KeywordTok{update}\NormalTok{(sc_lm_final,.}\OperatorTok{~}\NormalTok{.}\OperatorTok{+}\NormalTok{ComplexUnitsMade)}
\KeywordTok{kable}\NormalTok{(}\KeywordTok{tidy}\NormalTok{(sc_lm_}\DecValTok{5}\NormalTok{,}\DataTypeTok{conf.level =} \FloatTok{.05}\NormalTok{)[}\DecValTok{9}\OperatorTok{:}\DecValTok{10}\NormalTok{,],}\DataTypeTok{caption =} \StringTok{"ANOVA $lm_}\CharTok{\textbackslash{}\textbackslash{}}\StringTok{omega$ and $lm_}\CharTok{\textbackslash{}\textbackslash{}}\StringTok{omega+ComplexUnitsMade$"}\NormalTok{)}
\KeywordTok{kable}\NormalTok{(}\KeywordTok{anova}\NormalTok{(sc_lm_final,sc_lm_}\DecValTok{5}\NormalTok{),}\DataTypeTok{digits=}\DecValTok{2}\NormalTok{)}

\NormalTok{sc_lm_}\DecValTok{6}\NormalTok{<-}\KeywordTok{update}\NormalTok{(sc_lm_final,.}\OperatorTok{~}\NormalTok{.}\OperatorTok{-}\NormalTok{APM)}
\NormalTok{sc_lm_}\DecValTok{7}\NormalTok{<-}\KeywordTok{update}\NormalTok{(sc_lm_final,.}\OperatorTok{~}\NormalTok{.}\OperatorTok{-}\NormalTok{AssignToHotkeys)}

\KeywordTok{kable}\NormalTok{(}\KeywordTok{anova}\NormalTok{(sc_lm_final,sc_lm_}\DecValTok{6}\NormalTok{),}\DataTypeTok{digits=}\DecValTok{3}\NormalTok{,}\DataTypeTok{caption =} \StringTok{"ANOVA $lm_}\CharTok{\textbackslash{}\textbackslash{}}\StringTok{omega$ and $lm_}\CharTok{\textbackslash{}\textbackslash{}}\StringTok{omega-APM$"}\NormalTok{)}
\KeywordTok{kable}\NormalTok{(}\KeywordTok{anova}\NormalTok{(sc_lm_final,sc_lm_}\DecValTok{7}\NormalTok{),}\DataTypeTok{digits=}\DecValTok{3}\NormalTok{,}\DataTypeTok{caption =} \StringTok{"ANOVA $lm_}\CharTok{\textbackslash{}\textbackslash{}}\StringTok{omega$ and $lm_}\CharTok{\textbackslash{}\textbackslash{}}\StringTok{omega-AssignToHotkeys$"}\NormalTok{)}

\NormalTok{sc_lm_}\DecValTok{8}\NormalTok{<-}\KeywordTok{update}\NormalTok{(sc_lm_final,.}\OperatorTok{~}\NormalTok{.}\OperatorTok{-}\NormalTok{TotalHours)}
\NormalTok{sc_lm_}\DecValTok{9}\NormalTok{<-}\KeywordTok{update}\NormalTok{(sc_lm_final,.}\OperatorTok{~}\NormalTok{.}\OperatorTok{-}\NormalTok{HoursPerWeek)}

\KeywordTok{kable}\NormalTok{(}\KeywordTok{anova}\NormalTok{(sc_lm_final,sc_lm_}\DecValTok{8}\NormalTok{),}\DataTypeTok{digits=}\DecValTok{3}\NormalTok{,}\DataTypeTok{caption =} \StringTok{"ANOVA $lm_}\CharTok{\textbackslash{}\textbackslash{}}\StringTok{omega$ and $lm_}\CharTok{\textbackslash{}\textbackslash{}}\StringTok{omega-TotalHours$"}\NormalTok{)}
\KeywordTok{kable}\NormalTok{(}\KeywordTok{anova}\NormalTok{(sc_lm_final,sc_lm_}\DecValTok{9}\NormalTok{),}\DataTypeTok{digits=}\DecValTok{3}\NormalTok{,}\DataTypeTok{caption =} \StringTok{"ANOVA $lm_}\CharTok{\textbackslash{}\textbackslash{}}\StringTok{omega$ and $lm_}\CharTok{\textbackslash{}\textbackslash{}}\StringTok{omega-HoursPerWeek$"}\NormalTok{)}

\NormalTok{sc_lm_final<-}\KeywordTok{update}\NormalTok{(sc_lm_final,.}\OperatorTok{~}\NormalTok{.}\OperatorTok{-}\NormalTok{AssignToHotkeys}\OperatorTok{-}\NormalTok{HoursPerWeek)}
\KeywordTok{kable}\NormalTok{(}\KeywordTok{tidy}\NormalTok{(sc_lm_final,}\DataTypeTok{conf.level =} \FloatTok{.05}\NormalTok{),}\DataTypeTok{caption =} \StringTok{"$lm_}\CharTok{\textbackslash{}\textbackslash{}}\StringTok{omega$-HoursPerWeek-AssignToHotkeys"}\NormalTok{)}
\KeywordTok{kable}\NormalTok{(}\KeywordTok{confint}\NormalTok{(sc_lm_final))}

\NormalTok{sc_lm_rounded<-sc_lm_final}
\NormalTok{sc_lm_rounded}\OperatorTok{$}\NormalTok{fitted.values[sc_lm_rounded}\OperatorTok{$}\NormalTok{fitted.values}\OperatorTok{>}\DecValTok{7}\NormalTok{]<-}\DecValTok{7}
\NormalTok{sc_lm_rounded}\OperatorTok{$}\NormalTok{fitted.values<-}\KeywordTok{round}\NormalTok{(sc_lm_rounded}\OperatorTok{$}\NormalTok{fitted.values)}

\NormalTok{p1<-}\KeywordTok{ggplot}\NormalTok{(sc_lm_final, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{APM, }\DataTypeTok{y=}\KeywordTok{factor}\NormalTok{(LeagueIndex)))}\OperatorTok{+}\KeywordTok{geom_point}\NormalTok{()}\OperatorTok{+}\KeywordTok{geom_point}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{y=}\KeywordTok{fitted}\NormalTok{(sc_lm_final),}\DataTypeTok{color=}\StringTok{'Fitted'}\NormalTok{))}\OperatorTok{+}\KeywordTok{ggtitle}\NormalTok{(}\StringTok{"Fitted Values by }\CharTok{\textbackslash{}n}\StringTok{APM"}\NormalTok{)}\OperatorTok{+}\KeywordTok{theme_classic}\NormalTok{()}

\NormalTok{p2<-}\KeywordTok{ggplot}\NormalTok{(sc_lm_final, }\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{APM, }\DataTypeTok{y=}\KeywordTok{factor}\NormalTok{(LeagueIndex)))}\OperatorTok{+}\KeywordTok{geom_jitter}\NormalTok{() }\OperatorTok{+}\KeywordTok{geom_jitter}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{y=}\KeywordTok{round}\NormalTok{(sc_lm_rounded}\OperatorTok{$}\NormalTok{fitted.values),}\DataTypeTok{color=}\StringTok{'Fitted'}\NormalTok{))}\OperatorTok{+}\KeywordTok{ggtitle}\NormalTok{(}\StringTok{"Fitted Values Flattned/Rounded }\CharTok{\textbackslash{}n}\StringTok{ by APM , with jitter."}\NormalTok{)}\OperatorTok{+}\KeywordTok{theme_classic}\NormalTok{()}

\KeywordTok{grid.arrange}\NormalTok{(p1,p2,}\DataTypeTok{ncol=}\DecValTok{2}\NormalTok{)}

\NormalTok{sc_predicted<-}\KeywordTok{data.frame}\NormalTok{(}\StringTok{"LeagueIndex"}\NormalTok{=sc}\OperatorTok{$}\NormalTok{LeagueIndex,}\StringTok{"FlattenFitted"}\NormalTok{=sc_lm_rounded}\OperatorTok{$}\NormalTok{fitted.values)}

\NormalTok{sc_predicted}\OperatorTok{$}\NormalTok{correct<-sc_predicted}\OperatorTok{$}\NormalTok{LeagueIndex}\OperatorTok{==}\NormalTok{sc_predicted}\OperatorTok{$}\NormalTok{FlattenFitted}

\NormalTok{sc_predicted_agg<-sc_predicted}\OperatorTok{%>%}\KeywordTok{group_by}\NormalTok{(LeagueIndex)}\OperatorTok{%>%}
\StringTok{  }\KeywordTok{add_tally}\NormalTok{()}\OperatorTok{%>%}\KeywordTok{summarise}\NormalTok{(}\DataTypeTok{correct_perc=}\KeywordTok{sum}\NormalTok{(correct)}\OperatorTok{/}\KeywordTok{max}\NormalTok{(n),}\DataTypeTok{incorrect_perc=}\DecValTok{1}\OperatorTok{-}\KeywordTok{sum}\NormalTok{(correct)}\OperatorTok{/}\KeywordTok{max}\NormalTok{(n),}\DataTypeTok{n=}\KeywordTok{max}\NormalTok{(n))}\OperatorTok{%>%}\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{baserate=}\NormalTok{n}\OperatorTok{/}\DecValTok{3317}\NormalTok{)}\OperatorTok{%>%}\KeywordTok{select}\NormalTok{(LeagueIndex,correct_perc,baserate)}\OperatorTok{%>%}
\StringTok{  }\KeywordTok{melt}\NormalTok{(}\DataTypeTok{id=}\StringTok{"LeagueIndex"}\NormalTok{)}

\KeywordTok{ggplot}\NormalTok{(sc_predicted_agg,}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{x=}\NormalTok{LeagueIndex,}\DataTypeTok{y=}\NormalTok{value,}\DataTypeTok{fill=}\NormalTok{variable))}\OperatorTok{+}
\StringTok{   }\KeywordTok{geom_bar}\NormalTok{(}\DataTypeTok{stat=}\StringTok{"identity"}\NormalTok{, }\DataTypeTok{width=}\NormalTok{.}\DecValTok{5}\NormalTok{, }\DataTypeTok{position =} \StringTok{"dodge"}\NormalTok{)}\OperatorTok{+}\KeywordTok{theme_classic}\NormalTok{()}\OperatorTok{+}\KeywordTok{ylab}\NormalTok{(}\StringTok{"Correct %"}\NormalTok{)}\OperatorTok{+}\KeywordTok{ggtitle}\NormalTok{(}\StringTok{"Pseudo Confusion Matrix"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\hypertarget{references}{%
\section*{References}\label{references}}
\addcontentsline{toc}{section}{References}

\hypertarget{refs}{}
\leavevmode\hypertarget{ref-ViolinPlots}{}%
``A Complete Guide to Violin Plots \textbar{} Tutorial by Chartio.''
n.d. Accessed November 2, 2020.
\url{https://chartio.com/learn/charts/violin-plot-complete-guide/}.

\leavevmode\hypertarget{ref-AlphaStar}{}%
``AlphaStar: Mastering the Real-Time Strategy Game Starcraft Ii
\textbar{} Deepmind.'' n.d. Accessed November 2, 2020.
\url{https://deepmind.com/blog/article/alphastar-mastering-real-time-strategy-game-starcraft-ii}.

\leavevmode\hypertarget{ref-APM}{}%
``APM Definition.'' n.d. Accessed November 2, 2020.
\url{https://techterms.com/definition/apm}.

\leavevmode\hypertarget{ref-SC2IIWCSGlobal}{}%
``Congrats to the Starcraft Ii Wcs Global Finals Champion! - Blizzcon.''
n.d. Accessed October 26, 2020.
\url{https://blizzcon.com/en-us/news/23198508/congrats-to-the-starcraft-ii-wcs-global-finals-champion}.

\leavevmode\hypertarget{ref-ELO}{}%
``ELO Rating Sysem in Chess.'' n.d. Accessed November 8, 2020.
\url{https://chance.amstat.org/2020/09/chess/}.

\leavevmode\hypertarget{ref-Leagues2019}{}%
``Leagues: 2019 - Liquipedia - the Starcraft Ii Encyclopedia.'' n.d.
Accessed October 26, 2020.
\url{https://liquipedia.net/starcraft2/Battle.net_Leagues}.

\leavevmode\hypertarget{ref-OrdinalLog}{}%
``Ordinal Logistic Regression \textbar{} R Data Analysis Examples.''
n.d. Accessed October 27, 2020.
\url{https://stats.idre.ucla.edu/r/dae/ordinal-logistic-regression/}.

\leavevmode\hypertarget{ref-Perception}{}%
``Perception-Action Cycle - Models, Architectures, and Hardware
\textbar{} Vassilis Cutsuridis \textbar{} Springer.'' n.d. Accessed
October 29, 2020. \url{https://www.springer.com/gp/book/9781441914514}.

\leavevmode\hypertarget{ref-UCI}{}%
``UCI Machine Learning Repository: SkillCraft1 Master Table Dataset Data
Set.'' n.d. Accessed October 26, 2020.
\url{https://archive.ics.uci.edu/ml/datasets/SkillCraft1+Master+Table+Dataset}.

\leavevmode\hypertarget{ref-Smurf}{}%
``What Is a Smurf Account? Everything You Need to Know \textbar{}
Lol-Smurfs.'' n.d. Accessed November 2, 2020.
\url{https://www.lol-smurfs.com/blog/what-is-a-smurf-account}.

\leavevmode\hypertarget{ref-Winnings2019}{}%
``Winnings: 2019 - Liquipedia - the Starcraft Ii Encyclopedia.'' n.d.
Accessed October 26, 2020.
\url{https://liquipedia.net/starcraft2/Winnings/2019}.

\end{document}
